sets.exported={
    main={ name="Ipetam", augments={'Accuracy+7 Attack+7','"Dbl.Atk."+3','DMG:+15',}},
    sub={ name="Sandung", augments={'Accuracy+50','Crit. hit rate+5%','"Triple Atk."+3',}},
    ammo="Ginsen",
    head="Mummu Bonnet +1",
    body="Pillager's Vest +2",
    hands="Mummu Wrists +2",
    legs="Mummu Kecks",
    feet="Jute Boots +1",
    neck="Dualism Collar +1",
    waist="Aristo Belt",
    left_ear="Enchntr. Earring +1",
    right_ear="Delta Earring",
    left_ring="Valseur's Ring",
    right_ring="Asklepian Ring",
    back="Aisance Mantle +1",
}